[package]
org = "wso2"
name = "manage_batch_of_calls"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.engagements.calls"
version = "1.0.0"
repository = "local"